### ISSUE TITLE
API调用次数过多，请过几秒再试 The Github API is responding 403

### ISSUE THREAD

**Issue by sstoner** [hating/AwsomeGithub#1]
always when clicking "中国用户排行榜" and "全球用户排行榜"

**Comment by hating** [comment]
由于网站只有前端部分，直接通过CORS查询调用GithubAPI，所以当查询次数过多时，会出现403问题，请稍等片刻重新打开。
关于API的查询限制可以看这里：
https://developer.github.com/v3/search/#rate-limit

The site will respond 403 error when the query is too quick due to AwesomeGithub is a pure front-end project using CORS,and Github APIs has query limits.
You can read the limit rules from here:
https://developer.github.com/v3/search/#rate-limit
